import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./header/Header";
import AuthProvider from "./AuthProvider";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <Header />
          <Suspense fallback={<h1  className="text-3xl text-red-500">loading</h1>}>{children}</Suspense>
        </body>
      </AuthProvider>
    </html>
  );
}
